version: "3"
services:
  teste-postgres-compose:
    image: postgres:9.6
    container_name: assinatura
    ports:
      - "5434:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: springboot






